name: 'Jenkins AI'
description: 'Analyze Jenkins logs using AI and post results to Slack'
inputs:
  status-url:
    description: 'URL to the Jenkins job status page, used to fetch logs'
    required: true
  slack-access-token:
    description: 'Access token for Slack, used to match commit emails to usernames'
    required: true
  slack-message-thread-ts:
    description: 'Thread timestamp for Slack messages, used to post results in the same thread'
    required: true
  slack-channel:
    description: 'Slack channel or user ID where the message is posted'
    required: true
  gcp-sa:
    description: 'Google Cloud Service Account JSON, used for authentication with Google Cloud services'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
